
services:
  connect4-backend:
    build: .
    container_name: connect4-api
    ports:
      - "8000:8000"
    networks:
      - connect4-network
    volumes:
      - mcts-shared-code:/mcts:ro
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app:/mcts
    restart: unless-stopped

networks:
  connect4-network:
    external: true
    name: connect4-network

volumes:
  mcts-shared-code:
    external: true
    name: mcts-shared-code